
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './layout.module.css'
import {Header} from "@/app/components/Header/Header";
import {Sidebar} from "@/app/components/Sidebar/Sidebar";
import {Footer} from "@/app/components/Footer/Footer";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={styles.Wrapper}>
      <Header className={styles.Header} />
        <Sidebar className={styles.Sidebar} />
        <div className={styles.body}>
          {children}
        </div>
      <Footer className={styles.Footer} />
      </div>
      </body>
    </html>
  )
}